export const application = [
  'Breakfast',
  'Snack',
  'Bakery',
  'Pet Food',
  'Beverage',
  'Dairy',
  'Prepared Foods',
  'Confectionary',
  'Baby Food',
  'Seasonings',
  'Snack ?',
  'Dog Food',
  'Finished Product',
  'Spread',
  'Snack/Spread',
  'Sauce',
  'Meat',
  'Snacks',
  'Baby food',
  'Sweetener',
  'Cosmetics',
]

export const endProduct = [
  'Oatmeal',
  'Veggie Crisps',
  'Health Bar',
  'Whole Aronia Berries',
  'Cookie',
  'Cereal',
  'Veggie Bites',
  'RX Bar',
  'Dog Treats',
  'Wheat Beer',
  'Honey Butter',
  'Ricotta Cups',
  'Overnight Oats',
  'Pancake',
  'Sparkling Water',
  'Oatmeal Cup',
  'Chocolate Bar',
  'Ice Cream Bar',
  'Pasta',
  'Bon Bons',
  'Nutritional Drink',
  'Cookies',
  'Poppers',
  'Fruit Drink',
  'Pancake Mix',
  'Gelato',
  'Baby Food',
  'Bar',
  'Blueberry Granola',
  'Muffin a la Cup',
  'Lime Pepper Rub',
  'Blueberry Muffin',
  'Bagels',
  'Tea',
  'Mix-Ins',
  'Berry Rich Bites',
  'Beer',
  'Yogurt',
  'Smash Mallow',
  'Dog Food',
  'Donuts',
  'Snack Mix',
  'Fruit and Seed Bars',
  'Pop Tarts',
  'Protein Bar',
  'Alcoholic Cherry Cola',
  'Granola',
  'Gin',
  'Creative Food Ingredients Blueberry Cookie Crumble',
  'Chicken Stick',
  'Iced Tea',
  'Organic Oatmeal',
  'Muffin Mix',
  'Backpacking Kit',
  'Popcorn Seasonings',
  'Health Meal Bar',
  'Pet Food',
  'Blueberry Pie Bites',
  'Protein Bites',
  'Drink',
  'Almond Butter & Jelly Nut Butter',
  'Truffles',
  'Muffin',
  'Annie\'s Deluxe Macaroni',
  'Scones',
  'Protein Bark',
  'Whole Blueberries',
  'Jam Mixes',
  'Apple Chips and Strawberry Chips',
  'Hot Tea',
  'Almond Butter',
  'Spread',
  'Blueberry White Pepper Sauce',
  'Jerky',
  'Probiotic',
  'Nut Butter',
  'Citrus Rub',
  'Brownie',
  'Energy Bar',
  'Sausage',
  'Very Berry Cheerios',
  'ProBiotein Bar',
  'Quest Lemon Cake Protein Bar',
  'Fruit and Vegetable Powders',
  'Egg Kit',
  'Prepared Food',
  'Veggie Bar',
  'Keto Granola',
  'Smoothie',
  'Butter',
  'Natural Fruit Sugars',
  'White Bread',
  'Whole Strawberries',
  'Scrub',
  'Apple Pie',
  'Jam',
  'Cake',
  'Apricot & Peach IPA',
  'Bark'
]

export const manufacturer = [
  'Quaker',
  'Dirt Kitchen',
  'Pro Bar',
  'DiVera',
  'LeClerc',
  'General Mills',
  'Jif',
  'ZENB',
  'Kellogg Co',
  'Dog for Dog',
  'Anheuser-Busch',
  'Chef Sammy',
  'Real Good Dairy',
  'QTC Products',
  'PepsiCo',
  'Drink Recess Inc',
  'Libre Naturals',
  'Built Brands',
  'Nutrilink',
  'Crem Helado',
  'Feed the Machine',
  'Cheryl\'s Cookies',
  'KFC',
  'ANS Performance',
  'Scott Brothers',
  'Gerber',
  'Sunny Crunch Foods',
  'Birch Benders',
  'Tampico Spice',
  'ProBar',
  'Canyon Bakehouse',
  'Yogi Tea',
  'Silk',
  'HiLo Bites',
  'Almanac Beer',
  'Chobani',
  'Republic of Tea',
  'Smash Mallow',
  'Tyson',
  'Dosha',
  'Health Warrior',
  'Tea Guys',
  'Bubba\'s',
  'Bare Snacks',
  'Collective Arts Brewing',
  'Creative Food Ingredients',
  'Veterinary Prime Inc.',
  'Mighty Spark Foods',
  'Bob\'s Red Mill',
  'Straw Propeller',
  'Alpine Air',
  'Garrett\'s',
  'Cerebelly',
  'Powerful Foods',
  'Whole Food',
  'Melts',
  'Keto Farms',
  'Wildway LLC',
  'Evolution Fresh',
  'Nationwide Natural Foods',
  'Molson Coors Brewery',
  'Blue Moon Brewing Co',
  'Chuas',
  'Perfect Keto',
  'Ordnance Brewing',
  'Harry & David',
  'Good Snacks',
  'Sweet Logic',
  'Jacqueline\'s',
  'Notty',
  'Women\'s Bean Project',
  'Simply Balanced',
  'Montchevre',
  'Heiden\'s',
  'Tillamook',
  'Sunny Culture',
  'Unique Health Products',
  'Atkins',
  'Skratch Labs',
  'Cheryl\'s',
  'Trader Joes',
  'RC Bigelow',
  'Sun Opta Grains & Foods',
  'ProBiotein',
  'Miss Jones',
  'Quest Nutrition',
  'Spiceology',
  'Nana Joes',
  '1 Eatz',
  'Garden of Life',
  'Vili Vegetable',
  'Rich Products',
  'LivLo',
  'Sweet Nothings',
  'Stone Brewing',
  'Diamond of California',
  'Skout Organic',
  'Taste of Nature',
  'The Spice and Tea Exchange',
  'Ardent Mills',
  'Marich',
  'Nonni\'s',
  'Distrinctive Dog',
  'Palazzolos',
  'LUSH',
  'Smash Crispy',
  'Bitchin\' Sauce',
  'Miellerie St-Stanislas',
  'Merrick Pet Care',
  'Verb Caffeinated Energy Bar',
  'Oats Overnight',
  'Bodriggy Brewing',
  'Starbucks',
  'Kuli Kuli',
]

export const organicity = [
  'Inorganic',
  'Organic',
]

export const types = [
  'Fruit',
  'Vegetable',
]

export const mdProduct = [
  'Apple',
  'Aronia',
  'Banana',
  'Beet',
  'Bell Pepper',
  'Black Currant',
  'Blackberry',
  'Blueberry',
  'Broccoli',
  'Brussels Sprout',
  'Carrot',
  'Cauliflower',
  'Cherry',
  'Corn',
  'Cranberry',
  'Designer Grapes',
  'Elderberry',
  'Green Bean',
  'Kale',
  'Lemon',
  'Lime',
  'Mango',
  'Okra',
  'Orange',
  'Pea',
  'Peach',
  'Pineapple',
  'Pomegranate',
  'Potato',
  'Raspberry',
  'Rhubarb',
  'Spinach',
  'Squash',
  'Strawberry',
  'Sweet Potato',
  'Tomato',
  'Zucchini',
]

export const form = [
  'Whole',
  'Sliced',
  'Cubed',
  'Diced',
  'Tidbits',
  'Arils',
  'Fragment',
  'Powder',
]