export const application = [
  "Baby Food",
  "Bakery",
  "Beverage",
  "Breakfast",
  "Confectionary",
  "Cosmetics",
  "Dairy",
  "Finished Product",
  "Meat",
  "Pet Food",
  "Prepared Foods",
  "Sauce",
  "Seasonings",
  "Snack",
  "Spread",
  "Sweetener"
]

export const endProduct = [
  "Alcoholic Cherry Cola",
  "Almond Butter",
  "Annie's Deluxe Macaroni",
  "Apple Chips and Strawberry Chips",
  "Apple Pie",
  "Apricot & Peach IPA",
  "Baby Food",
  "Backpacking Kit",
  "Bagels",
  "Bar",
  "Bark",
  "Beer",
  "Berry Rich Bites",
  "Blueberry Granola",
  "Blueberry Muffin",
  "Blueberry Pie Bites",
  "Blueberry White Pepper Sauce",
  "Bon Bons",
  "Brownie",
  "Butter",
  "Cake",
  "Cereal",
  "Chicken Stick",
  "Chocolate Bar",
  "Citrus Rub",
  "Cookies",
  "Dog Food",
  "Dog Treats",
  "Donuts",
  "Drink",
  "Egg Kit",
  "Energy Bar",
  "Fruit Drink",
  "Fruit and Seed Bars",
  "Fruit and Vegetable Powders",
  "Gelato",
  "Gin",
  "Granola",
  "Health Bar",
  "Health Meal Bar",
  "Honey Butter",
  "Hot Tea",
  "Ice Cream Bar",
  "Iced Tea",
  "Jam",
  "Jerky",
  "Keto Granola",
  "Lime Pepper Rub",
  "Mix-Ins",
  "Muffin",
  "Muffin Mix",
  "Muffin a la Cup",
  "Natural Fruit Sugars",
  "Nut Butter",
  "Nutritional Drink",
  "Oatmeal",
  "Pancake Mix",
  "Pancakes",
  "Pasta",
  "Pop Tarts",
  "Popcorn Seasonings",
  "Poppers",
  "ProBiotein Bar",
  "Probiotic",
  "Protein Bar",
  "Protein Bark",
  "Protein Bites",
  "Quest Lemon Cake Protein Bar",
  "RX Bar",
  "Ricotta Cups",
  "Sausage",
  "Scones",
  "Scrub",
  "Smash Mallow",
  "Smoothie",
  "Snack Mix",
  "Sparkling Water",
  "Spread",
  "Tea",
  "Truffles",
  "Veggie Bar",
  "Veggie Bites",
  "Veggie Crisps",
  "Very Berry Cheerios",
  "Wheat Beer",
  "White Bread",
  "Whole Aronia Berries",
  "Whole Blueberries",
  "Whole Strawberries",
  "Yogurt"
]

export const manufacturer = [
  "1 Eatz",
  "ANS Performance",
  "Almanac Beer",
  "Alpine Air",
  "Anheuser-Busch",
  "Ardent Mills",
  "Atkins",
  "Bare Snacks",
  "Birch Benders",
  "Bitchin' Sauce",
  "Blue Moon Brewing Co",
  "Bob's Red Mill",
  "Bodriggy Brewing",
  "Bubba's",
  "Built Brands",
  "Canyon Bakehouse",
  "Cerebelly",
  "Chef Sammy",
  "Cheryl's",
  "Chobani",
  "Chuas",
  "Collective Arts Brewing",
  "Creative Food Ingredients",
  "Crem Helado",
  "DiVera",
  "Diamond of California",
  "Dirt Kitchen",
  "Distrinctive Dog",
  "Dog for Dog",
  "Dosha",
  "Drink Recess Inc",
  "Evolution Fresh",
  "Feed the Machine",
  "Garden of Life",
  "Garrett's",
  "General Mills",
  "Gerber",
  "Good Snacks",
  "Harry & David",
  "Health Warrior",
  "Heiden's",
  "HiLo Bites",
  "Jacqueline's",
  "Jif",
  "KFC",
  "Kellogg Co",
  "Keto Farms",
  "Kuli Kuli",
  "LUSH",
  "LeClerc",
  "Libre Naturals",
  "LivLo",
  "Marich",
  "Melts",
  "Miellerie St-Stanislas",
  "Mighty Spark Foods",
  "Miss Jones",
  "Mister Donut",
  "Molson Coors Brewery",
  "Montchevre",
  "Nana Joes",
  "Nationwide Natural Foods",
  "Nonni's",
  "Notty",
  "Nutrilink",
  "Oats Overnight",
  "Ordnance Brewing",
  "Palazzolos",
  "PepsiCo",
  "Perfect Keto",
  "Powerful Foods",
  "Pro Bar",
  "ProBar",
  "ProBiotein",
  "QTC Products",
  "Quaker",
  "Quest Nutrition",
  "RC Bigelow",
  "Real Good Dairy",
  "Republic of Tea",
  "Rich Products",
  "Scott Brothers",
  "Silk",
  "Simply Balanced",
  "Skout Organic",
  "Skratch Labs",
  "Smash Crispy",
  "Smash Mallow",
  "Spiceology",
  "Starbucks",
  "Stone Brewing",
  "Straw Propeller",
  "Sun Opta Grains & Foods",
  "Sunny Crunch Foods",
  "Sunny Culture",
  "Sweet Logic",
  "Sweet Nothings",
  "Tampico Spice",
  "Taste of Nature",
  "Tea Guys",
  "The Spice and Tea Exchange",
  "Tillamook",
  "Trader Joes",
  "Tyson",
  "Unique Health Products",
  "Verb Caffeinated Energy Bar",
  "Veterinary Prime Inc.",
  "Vili Vegetable",
  "Whole Food",
  "Wildway LLC",
  "Women's Bean Project",
  "Yogi Tea",
  "ZENB",
]

export const organicity = [
  'Inorganic',
  'Organic',
]

export const types = [
  'Fruit',
  'Vegetable',
]

export const mdProduct = [
  'Apple',
  'Aronia',
  'Banana',
  'Beet',
  'Bell Pepper',
  'Black Currant',
  'Blackberry',
  'Blueberry',
  'Broccoli',
  'Brussels Sprout',
  'Carrot',
  'Cauliflower',
  'Cherry',
  'Corn',
  'Cranberry',
  'Designer Grapes',
  'Elderberry',
  'Green Bean',
  'Kale',
  'Lemon',
  'Lime',
  'Mango',
  'Okra',
  'Orange',
  'Pea',
  'Peach',
  'Pineapple',
  'Pomegranate',
  'Potato',
  'Raspberry',
  'Rhubarb',
  'Spinach',
  'Squash',
  'Strawberry',
  'Sweet Potato',
  'Tomato',
  'Zucchini',
]

export const form = [
  'Arils',
  'Cubed',
  'Diced',
  'Fragment',
  'Powder',
  'Sliced',
  'Tidbits',
  'Whole',
]